<!-- AplicarDAnios -->
[h: data = arg(0)]
[h, if(pausear()==1): pause("data")]
[h: tokenAtk = getStrProp(data,"tokenAtk")]
[h: target = getStrProp(data,"target")]

[h: pv=getStrProp(data,"pv")]
[h: sumaPv = pv ]
[h: p1 = "PunVida"]
[h: p2 = "actiidad"]
[h: p3 = "aturd"]
[h: p4 = "sangre"]
[h: p5 = "iniciativa"]
[h: p6 = "simataque"]
[h: p7 = "derribar"]
[h: p8 = "matar"]
[h: p9 = "derrotar"]

[h: cd =countStrProp(data)]      

[r,COUNT(cd,""),code:{              
   [h: n = roll.count]     
   [h:key = indexKeyStrProp(data, roll.count)] 
   [h:value = indexValueStrProp(data, roll.count)]
      [h, if(  matches(key, ".*PunVida")): sumaPv = sumaPv + value]
[h, if(pausear()==1): pause("p1","value","key")]
      [r, if(  matches(key, ".*actividad")): AlterarActividad(target,value)]
[h, if(pausear()==1): pause("p2","value","key")]
      [r, if(  matches(key, ".*aturd")): Aturdir(target,value)]
[h, if(pausear()==1): pause("p3","value","key")]
      [r, if(  matches(key, ".*sangre")): Sangrar(target,value)]
[h, if(pausear()==1): pause("p4","value","key")]
      [r, if(  matches(key, ".*iniciativa")): Iniciativar(tokenAtk,value)]
[h, if(pausear()==1): pause("p5","value","key")]
      [r, if(  matches(key, ".*SumaAtaque")): SumarAlAtaque(tokenAtk,value)]
[h, if(pausear()==1): pause("p6","value","key")]
      [r, if( value==1 && matches(key, ".*derribado")): Derribar(target,value)]     
[h, if(pausear()==1): pause("p7","value","key")]
      [r, if( value==1 && matches(key, ".*muerto")): Matar(target,value)]
[h, if(pausear()==1): pause("p8","value","key")]
      [r, if( value==1 && matches(key, ".*derrotado")): derrotar(target,value)]
[h, if(pausear()==1): pause("p9","value","key")]

}]

[r,if(sumaPv > 0): PerderPV(target,sumaPv) ; target + " No recibe danios." ]
[h: closeFrame("calculoDanioInput")]

[h: ga = getProperty("GolpeActual",target)]
[h: dr = getStrProp(ga,"danioRecibido")]
[h: ga = setStrProp(ga,"danioRecibido",number(dr) + sumaPv)]
[h: ga = setProperty("GolpeActual",ga,target)]
